# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_question', models.CharField(max_length=100)),
                ('qa_answer_sql', models.TextField()),
                ('qa_created_at', models.DateField()),
            ],
        ),
    ]
