# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_director_director_question_manager_manager_question_number_of_staff_product_questions_products_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='qa_answer_fucntion',
            field=models.CharField(choices=[('0', 'freshman'), ('1', 'sophomore'), ('2', 'junior'), ('3', 'senior')], default='freshman', max_length=1),
        ),
    ]
