# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_qa_qa_answer_fucntion'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='qa_answer_fucntion',
            field=models.CharField(choices=[('0', 'Mr'), ('1', 'Sir'), ('2', 'Mrs'), ('3', 'Lady')], default='Mr', max_length=1),
        ),
    ]
