# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_auto_20190301_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Sir', 'Sir'), ('Mrs', 'Mrs'), ('Lady', 'Lady')], default='Mr', max_length=5),
        ),
        migrations.AlterField(
            model_name='manager',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Sir', 'Sir'), ('Mrs', 'Mrs'), ('Lady', 'Lady')], default='Mr', max_length=5),
        ),
    ]
