# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-01 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0015_auto_20190301_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_questions',
            new_name='Product_question',
        ),
    ]
