# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0016_auto_20190301_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_question',
            new_name='Product_list_question',
        ),
        migrations.RenameField(
            model_name='product_count_question',
            old_name='product_question',
            new_name='product_count_question',
        ),
        migrations.RenameField(
            model_name='product_list_question',
            old_name='product_question',
            new_name='product_list_question',
        ),
    ]
