# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0018_auto_20190303_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Lady', 'Lady'), ('Sir', 'Sir')], default='Mr', max_length=5),
        ),
    ]
